openapi: 3.0.0
x-stoplight:
  id: qjda1cy25d009
info:
  title: Courses
  version: '1.0'
  description: 'API zaměřené na partnery, kteří chtějí...'
  contact:
    name: Miroslav Holec
    url: 'https://www.miroslavholec.cz'
    email: mirek@miroslavholec.cz
  license:
    name: MIT
servers:
  - url: 'https://localhost:3000'
    description: local
  - url: 'https://restdemo.miroslavholec.cz/api'
    description: production
paths:
  /courses:
    get:
      summary: Získání seznamu kurzů
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Courses'
        '500':
          $ref: '#/components/responses/500-Server-Error'
      operationId: GetCourses
      parameters:
        - schema:
            type: string
          in: query
          name: name
          description: Název kurzu
        - schema:
            type: integer
            default: 10
          in: query
          name: take
        - schema:
            type: integer
            default: 0
          in: query
          name: skip
    post:
      summary: Vytvoření nového kurzu
      operationId: CreateCourse
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'
        '500':
          $ref: '#/components/responses/500-Server-Error'
      description: Endpoint pro **vytváření kurzů** v systému e-learningu
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CourseCreate'
          application/xml:
            schema:
              $ref: '#/components/schemas/CourseCreate'
        description: Nastavuje kurz
  '/courses/{id}':
    parameters:
      - schema:
          type: integer
        name: id
        in: path
        required: true
        description: Unikátní ID kurzu
    get:
      summary: Vrácení kurzu dle ID
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'
              examples:
                Standard-200-Id-1:
                  value:
                    id: 1
                    title: Školení ASP.NET Core
                    date: '2019-08-24T14:15:22Z'
                    price: 900
                    attendees: 1
                Standard-200-Id-2:
                  value:
                    id: 2
                    title: Design REST API
                    date: '2019-08-24T14:15:22Z'
                    price: 0
                    attendees: 100
        '500':
          $ref: '#/components/responses/500-Server-Error'
      operationId: GetCourseById
components:
  schemas:
    Course:
      title: Course
      x-stoplight:
        id: ca00375y2sf4o
      type: object
      description: Školící kurz
      properties:
        id:
          type: integer
          format: int32
          description: Unikátní identifikátor
        title:
          type: string
        date:
          type: string
          format: date-time
        price:
          type: number
          format: double
        attendees:
          type: integer
          format: int32
          description: Počet účastníků se zaplaceným kurzovným
      x-examples:
        Standard:
          id: 1
          title: Školení ASP.NET Core
          date: '2019-08-24T14:15:22Z'
          price: 999
          attendees: 10
    Courses:
      title: Courses
      x-stoplight:
        id: frxymly7qj9tl
      type: object
      description: Kolekce kurzů
      properties:
        items:
          type: array
          description: Seznam kurzů
          items:
            $ref: '#/components/schemas/Course'
        totalCount:
          type: integer
          format: int32
          description: Celkový počet kurzů dle filtru
    CourseCreate:
      title: CourseCreate
      x-stoplight:
        id: 0qtkvmtjnyi2r
      type: object
      description: Vytvářený kurz
      properties:
        title:
          type: string
          maxLength: 100
        price:
          type: number
          format: double
          minimum: 0
          maximum: 9000
        date:
          type: string
          format: date-time
          description: Datum konání
      required:
        - title
        - price
        - date
    ProblemDetails:
      title: ProblemDetails
      x-stoplight:
        id: xspr47ndjw6pl
      type: object
      properties:
        title:
          type: string
      description: Chybový objekt (univerzální pro všechny status codes)
  responses:
    500-Server-Error:
      description: Chyba na straně serveru
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
          examples:
            Standard:
              value:
                title: Internal Server Error
